### ISSUE TITLE
Enlaces a capítulos incorrectos

### ISSUE THREAD

**Issue by akindofcode** [akindofcode/JavaScript-Elocuente#3]
En el apartado 'Descripción general de este libro' (Introducción) hay varios enlaces a capítulos que no funcionan:

Capítulos 5(orden_superior) y 6(objeto)
Capítulos 13(navegador) a 19(paint)
Capítulos 14(dom) y 17(canvas)

**Comment by CodeKommissar** [comment]
Listo, ya hice el pull request para arreglar esos enlaces.

**Comment by akindofcode** [comment]
Gracias @CodeKommissar
